version: "3.4"

services:

  sosound-tools:
    image: sosound-tools
    container_name: sosound-tools
    network_mode: host
    volumes:
      # local dir hosting music file
      - /home/master/Music:/root/Music

      # custom youtube-dl and cookies configuration
      - ./etc/youtube-dl.conf:/root/.config/sosound/youtube-dl.conf
      - ./etc/.cookies.txt:/root/.cookies.txt

      # fetchSound and syncSound configuration file
      - ./etc/dl.conf:/root/.config/sosound/dl.conf
      - ./etc/sync.conf:/root/.config/sosound/sync.conf

      # dev mode
      - .:/app

      # persist logs and locks
      - dataLogs:/root/.config/sosound/logs
      - dataLocker:/root/.config/sosound/lock
    env_file:
      - .env

volumes:
  dataLocker:
  dataLogs:
