version: "3.4"

services:

  sosound-tools:
    image: sosound-tools
    container_name: sosound-tools
    network_mode: host
    volumes:
      # local dir hosting music file
      - /home/master/Music:/root/Music

      # custom youtube-dl and cookies configuration
      - ./etc/youtube-dl.conf:/root/.config/music_helper/youtube-dl.conf
      - /home/master/.cookies.txt:/root/.cookies.txt

      # fetchSound and syncSound configuration file
      - ./etc/dl.conf:/root/.config/music_helper/dl.conf
      - ./etc/sync.conf:/root/.config/music_helper/sync.conf

      # share logs with the system
      # - ./etc/logs:/root/.config/music_helper/logs

      # dev mode
      - .:/app

      # persist logs and locks
      - dataLogs:/root/.config/music_helper/logs
      - dataLocker:/root/.config/music_helper/lock
    env_file:
      - .env

volumes:
  dataLocker:
  dataLogs:
